name: selenium

# Controls when the workflow will run
on:
  schedule:
    # 北京时间 01:00 04:00 07:00 10:00
    # - cron: '0 17,20,23,2 * * *'
    - cron: ''

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Python env
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Install requiments
      - name: Install selenium
        run: pip install selenium
      
      # Task running
      - name: Run selenium
        run: |
          sudo cp chromedriver /usr/bin
          sudo chmod -R 777 /usr/bin/chromedriver
          python main.py
