name: auto_lzu_check_in

on:
  schedule:
    # 在北京时间 06:00, 08:00, 10:00 自动执行
    - cron: '0 22,0,2 * * *'

  # 允许手动执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # pull 当前库
      - uses: actions/checkout@v2

      - name: Set up Python env
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -q selenium webdriver-manager fake_useragent

      - name: Run main.py
        run: python main.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
