name: auto_lzu_check_in

on:
  # schedule:
    # 在北京时间 06:00, 08:00, 10:00 自动执行
    # - cron: '0 22,0,2 * * *'

  # 允许手动执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # pull 当前库
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -q selenium webdriver-manager fake_useragent packaging

      - name: Run main.py
        run: python main.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
